export const ErrorCodes = {
  // Auth
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_VERIFICATION_SENT: 'EMAIL_VERIFICATION_SENT',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  VERIFICATION_TOKEN_NOT_FOUND: 'VERIFICATION_TOKEN_NOT_FOUND',
  INVALID_LINK: 'INVALID_LINK',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  NO_TOKEN_PROVIDED: 'NO_TOKEN_PROVIDED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  ACCESS_DENIED: 'ACCESS_DENIED',

  // Users
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  NO_PROFILE_AVATAR: 'NO_PROFILE_AVATAR',
  NO_FILE_PROVIDED: 'NO_FILE_PROVIDED',
  USERNAME_ALREADY_IN_USE: 'USERNAME_ALREADY_IN_USE',

  // Storage
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_DELETE_FAILED: 'FILE_DELETE_FAILED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',

  // Mail
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
} as const;
